"""add session tables

Revision ID: 05e6184ab0ff
Revises: 757cf0c68bd0
Create Date: 2026-04-17 15:44:16.043783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05e6184ab0ff'
down_revision: Union[str, Sequence[str], None] = '757cf0c68bd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cartsession_job_id'), table_name='cartsession')
    op.drop_table('cartsession')
    op.drop_index(op.f('ix_adaptersession_adapter_id'), table_name='adaptersession')
    op.drop_table('adaptersession')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adaptersession',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('adapter_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('encrypted_state', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('adaptersession_pkey'))
    )
    op.create_index(op.f('ix_adaptersession_adapter_id'), 'adaptersession', ['adapter_id'], unique=True)
    op.create_table('cartsession',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('encrypted_cookies', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cart_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('cartsession_pkey'))
    )
    op.create_index(op.f('ix_cartsession_job_id'), 'cartsession', ['job_id'], unique=False)
    # ### end Alembic commands ###
