"""Adapter for the "standard" (non-Great-Walk) DOC booking flow.

The Great Walk booking site uses a single search form and a unified result
grid (handled by ``doc_great_walk.DocGreatWalkAdapter``). Standard huts,
campsites, lodges and Mueller Hut-style sites use a different booking flow
accessed via URLs of the form::

    https://bookings.doc.govt.nz/Web/#!park/{park_id}/{facility_id}

Note: an older version of this code used ``Default.aspx`` as the path, which
now returns a 404.  The SPA root is ``/Web/`` — same as the scraper's
``LANDING_URL`` (``/Web/#!results``).

On that page:
  * The date range is edited via a custom date-range popup (clicking the
    "1 Night · Wed, Apr 01 - Thu, Apr 02" booking bar opens a two-month
    calendar where the user picks a start day, then an end day).
  * Availability is shown in a wide "Site List" table with a "Site"
    column, "Available # of People" row, "Number of sites available"
    row, and one column per day in the selected range.

The port of the Mueller Hut logic from the standalone ``watch.ts`` script
lives in this file.
"""

from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass
from datetime import datetime, timedelta
from pathlib import Path

from playwright.async_api import Locator, Page, TimeoutError as PlaywrightTimeoutError

from app.adapters.base import (
    AvailabilityResult,
    AvailabilityStatus,
    BookingResult,
    ParamField,
)
from app.adapters.base_doc import BaseDOCAdapter, MONTHS, PEOPLE_OPTIONS


logger = logging.getLogger(__name__)


MONTH_SHORT = {m: m[:3] for m in MONTHS}


# NOTE: an earlier commit tried to bake DOC's listbox options into a
# constant here, but the listbox `id` attributes turn out to be opaque
# "place" ids — not park_id / facility_id — and therefore can't be used
# to build a booking URL. The real catalog lives in doc_standard_huts.json
# and is produced by backend/scripts/scrape_standard_huts.py, which walks
# the booking site end-to-end to capture the ``(park_id, facility_id)``
# pairs needed for ``!park/{park_id}/{facility_id}``.


# -------------------------------------------------------------------------- #
# Hut catalog — loaded from doc_standard_huts.json (generated by
# backend/scripts/scrape_standard_huts.py). Kept in-memory; cheap to
# reload if the file is updated at runtime.
# -------------------------------------------------------------------------- #

_HUT_CATALOG_PATH = Path(__file__).with_name("doc_standard_huts.json")

# The option string the frontend sees / sends back. Putting the hut name
# first makes alphabetic sort useful; embedding the IDs keeps the value
# self-describing so we don't need a separate lookup at submit time.
#   "Mueller Hut (747/2487) — Aoraki/Mount Cook National Park"
_FACILITY_OPTION_RE = re.compile(
    r"^(?P<hut>.+?)\s*\((?P<park>\d+)/(?P<facility>\d+)\)(?:\s*—\s*(?P<park_name>.+))?$"
)


def _format_facility_option(facility: dict, park_id: str, park_name: str) -> str:
    """Build the canonical option string for a single facility.

    Format: ``"Mueller Hut (747/2487) — Aoraki/Mount Cook National Park"``
    The embedded ``(park_id/facility_id)`` pair is what ``_FACILITY_OPTION_RE``
    unpacks at request time, so this format must not change without also
    updating that regex.
    """
    base = f"{facility['facility_name']} ({park_id}/{facility['facility_id']})"
    park = park_name.strip()
    return f"{base} — {park}" if park else base


def _parse_facility_option(value: str) -> tuple[str, str, str] | None:
    m = _FACILITY_OPTION_RE.match(value.strip())
    if not m:
        return None
    return m.group("park"), m.group("facility"), m.group("hut").strip()


def _load_hut_catalog() -> list[dict]:
    """Return the list of park dicts from doc_standard_huts.json.

    Each dict has the shape::

        {
          "park_id": "747",
          "park_name": "Aoraki/Mount Cook National Park",
          "facilities": [
            {"facility_id": "2487", "facility_name": "Mueller Hut"},
            ...
          ]
        }

    Parks are sorted alphabetically by park_name; facilities within each
    park are sorted alphabetically by facility_name.

    Returns an empty list (rather than raising) if the file is missing or
    malformed, so a broken catalog file doesn't prevent the rest of the
    adapter surface from loading.
    """
    try:
        raw = json.loads(_HUT_CATALOG_PATH.read_text())
    except FileNotFoundError:
        logger.warning("doc_standard_huts.json not found at %s — facility list empty", _HUT_CATALOG_PATH)
        return []
    except Exception as e:
        logger.error("failed to load doc_standard_huts.json: %s", e)
        return []

    parks = raw.get("parks") or []
    # Sort parks alphabetically; sort facilities within each park.
    parks = sorted(parks, key=lambda p: (p.get("park_name") or "").lower())
    for park in parks:
        park["facilities"] = sorted(
            park.get("facilities") or [],
            key=lambda f: (f.get("facility_name") or "").lower(),
        )
    return parks


def _facility_options_tree() -> list[dict]:
    """Build the grouped options tree for the frontend's <SelectGroup> rendering.

    Returns a list of ``{"group": park_name, "items": [opt_str, …]}`` dicts,
    one per park, in park_name alphabetical order.
    """
    result = []
    for park in _load_hut_catalog():
        park_id = park.get("park_id", "")
        park_name = park.get("park_name", "")
        items = [
            _format_facility_option(f, park_id, park_name)
            for f in park.get("facilities") or []
        ]
        if items:
            result.append({"group": park_name, "items": items})
    return result



# -------------------------------------------------------------------------- #
# Helpers that don't need adapter state
# -------------------------------------------------------------------------- #

@dataclass
class _DateParts:
    day: int
    month: str       # full month name, e.g. "April"
    year: int

    @classmethod
    def from_ddmmyyyy(cls, s: str) -> "_DateParts":
        dd, mm, yyyy = s.split("/")
        return cls(day=int(dd), month=MONTHS[int(mm) - 1], year=int(yyyy))


def _normalize(s: str | None) -> str:
    return re.sub(r"\s+", " ", s or "").strip()


def _parse_site_cell_status(site_cell_html: str) -> tuple[bool, str, str | None]:
    """Return ``(bookable, aria_status, icon)`` for a site-list cell button."""
    icon_match = re.search(
        r"(?:Keechma/icons|themes/[^/]+)/([^\"'()/]+)\.svg",
        site_cell_html, re.IGNORECASE,
    )
    icon = icon_match.group(1) if icon_match else None

    aria_label_match = re.search(
        r'aria-label=["\'][^"\']*-\s*([^"\']+)["\']', site_cell_html, re.IGNORECASE
    )
    aria_status = aria_label_match.group(1).strip().lower() if aria_label_match else ""

    cell_is_bookable = bool(re.search(r'tabindex=["\']0["\']', site_cell_html))
    if not cell_is_bookable and aria_status:
        cell_is_bookable = not re.search(
            r"booked|closed|unavailable|not.available|outside|locked|walk-?in",
            aria_status,
        )

    return cell_is_bookable, aria_status, icon


def _build_booking_bar_regexes(start: _DateParts, end: _DateParts) -> dict:
    """Regexes that match the booking-bar label once the date range is set.

    The bar is typically rendered as e.g. "1 Night Wed, Apr 01 - Thu, Apr 02"
    but the day number may or may not have a leading zero, and DOC has been
    observed using either the short ("Apr") or full ("April") month name.
    """
    s_m = MONTH_SHORT[start.month]
    e_m = MONTH_SHORT[end.month]

    s_month_group = f"({s_m}|{start.month})"
    e_month_group = f"({e_m}|{end.month})"

    start_pat = rf"{s_month_group}\s*0?{start.day}\b"
    end_pat = rf"{e_month_group}\s*0?{end.day}\b"

    range_pat = re.compile(rf"{start_pat}.*[\-\u2013].*{end_pat}", re.IGNORECASE)
    return {
        "range": range_pat,
        "start": re.compile(start_pat, re.IGNORECASE),
        "end": re.compile(end_pat, re.IGNORECASE),
    }


# -------------------------------------------------------------------------- #
# Adapter
# -------------------------------------------------------------------------- #

class DocStandardHutAdapter(BaseDOCAdapter):
    """Availability + hold adapter for the "regular" DOC booking flow.

    Facilities are selected from the scraped catalog (doc_standard_huts.json)
    via the ``facility`` param, which encodes the park ID, facility ID, and
    names in a single option string parsed by ``_parse_facility_option``.
    """

    adapter_id = "doc_standard_hut"
    name = "NZ DOC Standard Hut/Campsite"
    base_url = "https://bookings.doc.govt.nz/Web/#!park/{park_id}/{facility_id}"

    # ---------------------------------------------------------------- #
    # Param schema
    # ---------------------------------------------------------------- #

    @classmethod
    def param_fields(cls) -> list[ParamField]:
        options_tree = _facility_options_tree()

        return [
            ParamField(
                key="facility",
                label="Hut / Campsite",
                type="select",
                options_tree=options_tree,
                default="",
                required=True,
            ),
            ParamField(
                key="nights",
                label="Nights",
                type="number",
                default=1,
            ),
            ParamField(
                key="date",
                label="Start Date",
                type="date",
                required=True,
            ),
            ParamField(
                key="occupants",
                label="Occupants",
                type="text",
                default=(
                    '[{"first_name": "","last_name": "",'
                    '"category": "NZ Adult (18+)","country": "New Zealand",'
                    '"age": "","gender": "Male"}]'
                ),
                required=True,
            ),
            ParamField(
                key="people",
                label="People",
                type="select",
                options=PEOPLE_OPTIONS,
                default="2",
            ),
        ]

    # ---------------------------------------------------------------- #
    # Site resolution
    # ---------------------------------------------------------------- #

    def _resolve_site(self, params: dict) -> tuple[str, str, str]:
        """Return ``(park_id, facility_id, hut_name)`` from the ``facility``
        param string.  Raises ``ValueError`` if the string is missing or
        doesn't match the expected format.
        """
        facility = str(params.get("facility") or "").strip()
        if facility:
            parsed = _parse_facility_option(facility)
            if parsed is not None:
                return parsed

        raise ValueError(
            "DocStandardHutAdapter requires a valid `facility` option string"
        )

    # ---------------------------------------------------------------- #
    # URL helpers
    # ---------------------------------------------------------------- #

    def _url_for(self, params: dict) -> str:
        park_id, facility_id, _ = self._resolve_site(params)
        return self.base_url.format(park_id=park_id, facility_id=facility_id)

    def _date_range(self, params: dict) -> tuple[_DateParts, _DateParts]:
        start = _DateParts.from_ddmmyyyy(params["date"])
        nights = int(params.get("nights", 1))
        end_dt = datetime(start.year, MONTHS.index(start.month) + 1, start.day) \
            + timedelta(days=max(nights, 1))
        end = _DateParts(
            day=end_dt.day,
            month=MONTHS[end_dt.month - 1],
            year=end_dt.year,
        )
        return start, end

    # ---------------------------------------------------------------- #
    # Small Playwright helpers
    # ---------------------------------------------------------------- #

    async def _first_visible(self, loc: Locator) -> Locator:
        count = await loc.count()
        for i in range(count):
            item = loc.nth(i)
            try:
                if await item.is_visible():
                    return item
            except Exception:
                continue
        raise RuntimeError("No visible matching locator found")

    # ---------------------------------------------------------------- #
    # Booking-bar helpers (the "1 Night · Wed, Apr 01 - Thu, Apr 02" bar)
    # ---------------------------------------------------------------- #

    # Matches either a full "Mon, Apr 01 - Tue, Apr 02" range or half of one
    # plus "End Date" (which is what DOC shows when only the start has been
    # picked so far).
    _DATE_RANGE_TEXT_RE = re.compile(
        r"[A-Z][a-z]{2},\s*[A-Z][a-z]{2}\s*\d{2}\s*-\s*"
        r"([A-Z][a-z]{2},\s*)?[A-Z][a-z]{2}\s*\d{2}"
        r"|[A-Z][a-z]{2},\s*[A-Z][a-z]{2}\s*\d{2}\s*-\s*End Date"
    )
    _NIGHT_TEXT_RE = re.compile(r"^\d+\s*Night(s)?$", re.IGNORECASE)

    async def _get_date_range_locator(self, page: Page) -> Locator:
        return await self._first_visible(page.get_by_text(self._DATE_RANGE_TEXT_RE))

    async def _get_night_locator(self, page: Page) -> Locator:
        return await self._first_visible(page.get_by_text(self._NIGHT_TEXT_RE))

    async def _read_booking_bar_text(self, page: Page) -> str:
        """Return the full booking-bar string, normalised.

        The bar sits in a container with both "1 Night" and "Wed, Apr 01 -
        Thu, Apr 02" children. We anchor on the date-range text and climb
        one level up to capture the surrounding container.
        """
        date_loc = await self._get_date_range_locator(page)
        container = date_loc.locator("xpath=ancestor::div[1]")
        try:
            txt = await container.inner_text()
        except Exception:
            txt = await date_loc.inner_text()
        return _normalize(txt)

    # ---------------------------------------------------------------- #
    # Datepicker popup helpers
    # ---------------------------------------------------------------- #

    # Selector that matches the datepicker popup container when it's open.
    # The DOC booking SPA uses react-datepicker under the hood.
    _POPUP_SEL = ".react-datepicker-popper, .react-datepicker"

    async def _datepicker_popup(self, page: Page) -> Locator | None:
        """Return the visible datepicker popup locator, or None if closed."""
        for sel in self._POPUP_SEL.split(", "):
            loc = page.locator(sel.strip()).first
            try:
                if await loc.count() > 0 and await loc.is_visible():
                    return loc
            except Exception:
                continue
        return None

    async def _is_datepicker_open(self, page: Page) -> bool:
        """Return True if the calendar picker is currently visible.

        Uses the "Su" weekday-column header as the primary signal — it appears
        in the open calendar's day-name row and is not present elsewhere on the
        DOC booking page.  Falls back to CSS-class selectors as a secondary
        check.
        """
        # Primary: the "Su" column header only appears when the calendar is open
        try:
            su = page.get_by_text(re.compile(r"^Su$")).first
            if await su.count() > 0 and await su.is_visible():
                return True
        except Exception:
            pass
        # Secondary: react-datepicker CSS class selectors
        return (await self._datepicker_popup(page)) is not None

    async def _close_datepicker(self, page: Page) -> None:
        """Close the datepicker popup if it's open.

        Tries Escape first (cleanest), then a click on a neutral corner of the
        page body as a fallback.
        """
        if not await self._is_datepicker_open(page):
            return
        try:
            await page.keyboard.press("Escape")
            await page.wait_for_timeout(400)
        except Exception:
            pass
        if await self._is_datepicker_open(page):
            # Fallback: click a neutral spot (top-left corner of the viewport)
            try:
                await page.mouse.click(5, 5)
                await page.wait_for_timeout(400)
            except Exception:
                pass

    async def _open_datepicker(self, page: Page) -> None:
        """Open the date-range popup by clicking the booking bar.

        If the popup is already open (the site sometimes auto-opens it on page
        load), return immediately without toggling it closed.

        Tries clicking progressively broader ancestors of the date-range text
        until we see a known popup signal (month label, weekday header, etc.).
        """
        # Already open — nothing to do
        if await self._is_datepicker_open(page):
            logger.debug("Datepicker already open — skipping open click")
            return

        date_text = await self._get_date_range_locator(page)
        night_text = await self._get_night_locator(page)

        candidates: list[Locator] = [
            date_text,
            date_text.locator("xpath=ancestor::div[1]"),
            date_text.locator("xpath=ancestor::div[2]"),
            date_text.locator("xpath=ancestor::div[3]"),
            night_text,
            night_text.locator("xpath=ancestor::div[1]"),
            night_text.locator("xpath=ancestor::div[2]"),
        ]

        popup_signals = [
            page.get_by_text(re.compile(r"Furthest Arrival Date", re.IGNORECASE)).first,
            page.get_by_text(
                re.compile(
                    r"^(January|February|March|April|May|June|July|August"
                    r"|September|October|November|December)\s+\d{4}$"
                )
            ).first,
            page.get_by_text(re.compile(r"^Su$")).first,  # weekday header
        ]

        for i, target in enumerate(candidates):
            try:
                if await target.count() == 0:
                    continue
                try:
                    await target.scroll_into_view_if_needed()
                except Exception:
                    pass
                await target.click(force=True, timeout=4000)
            except Exception as e:
                logger.debug(f"openDatepicker candidate {i} click failed: {e}")
                continue

            # Poll for a popup signal for up to 4s
            for _ in range(27):
                if await self._is_datepicker_open(page):
                    return
                for sig in popup_signals:
                    try:
                        if await sig.count() > 0 and await sig.is_visible():
                            return
                    except Exception:
                        pass
                await page.wait_for_timeout(150)

        await self.snapshot(page, "datepicker_did_not_open")
        raise RuntimeError(
            "Could not open standard-hut datepicker by clicking the booking bar"
        )

    # ---------------------------------------------------------------- #
    # Date-range calendar popup
    # ---------------------------------------------------------------- #

    async def _visible_month_labels(self, scope: Page | Locator) -> list[str]:
        try:
            raw = await scope.get_by_text(
                re.compile(
                    r"^(January|February|March|April|May|June|July|August"
                    r"|September|October|November|December)\s+\d{4}$"
                )
            ).all_inner_texts()
        except Exception:
            return []
        return [_normalize(t) for t in raw if _normalize(t)]

    async def _popup_has_month(self, page: Page, month: str, year: int) -> bool:
        labels = await self._visible_month_labels(page)
        want = f"{month} {year}".lower()
        return any(lbl.lower() == want for lbl in labels)

    async def _click_month_nav(self, page: Page, direction: str) -> None:
        """Click the calendar's prev/next-month chevron.

        Scopes the button search to the datepicker popup so we don't
        accidentally click page-level buttons (accordions, breadcrumb arrows,
        share buttons, etc.) that happen to be left-most / right-most on the
        page.  Falls back to page-wide search only if the popup can't be
        identified.
        """
        popup = await self._datepicker_popup(page)
        scope: Page | Locator = popup if popup is not None else page

        buttons = scope.locator("button")
        count = await buttons.count()
        candidates: list[tuple[int, float]] = []  # (index, x-position)
        for i in range(count):
            b = buttons.nth(i)
            try:
                box = await b.bounding_box()
                if not box or not await b.is_visible():
                    continue
            except Exception:
                continue
            candidates.append((i, box["x"]))

        if candidates:
            if direction == "next":
                chosen_idx = max(candidates, key=lambda c: c[1])[0]
            else:
                chosen_idx = min(candidates, key=lambda c: c[1])[0]
            await buttons.nth(chosen_idx).click(force=True, timeout=5000)
            return

        # Fallback: aria-label or text-based selectors
        aria = "next" if direction == "next" else "previous"
        text_sel = ">" if direction == "next" else "<"
        for sel in [
            f'button[aria-label*="{aria}" i]',
            f'button:has-text("{text_sel}")',
        ]:
            loc = page.locator(sel).first
            if await loc.count() > 0:
                await loc.click(force=True, timeout=5000)
                return

        raise RuntimeError(f"Could not click {direction} month navigation")

    async def _ensure_month_visible(self, page: Page, month: str, year: int) -> None:
        for _ in range(24):
            if await self._popup_has_month(page, month, year):
                return
            await self._click_month_nav(page, "next")
            await page.wait_for_timeout(300)
        raise RuntimeError(f"Could not bring {month} {year} into calendar view")

    async def _click_day_in_visible_month(
        self, page: Page, month: str, year: int, day: int
    ) -> None:
        """Pick a day number inside the currently-visible ``month year`` block.

        Strategy (in order):
        1. Role-based: try button / option / gridcell with aria-label patterns.
        2. Ancestor-scoped text: find the month heading, walk up the DOM to its
           containing section (depths 1–5), then click the first element whose
           full text is exactly ``{day}``.  This is scoped to the right calendar
           panel so it can't hit day numbers in the booking bar or other panels.
        3. JS fallback: use ``page.evaluate`` to walk the live DOM, find the
           month heading by innerText, and click the first leaf element whose
           text is the day number — works regardless of CSS class names.
        """
        day_re = re.compile(rf"^{day}$")
        day_str = str(day)
        month_year = f"{month} {year}"

        # ── 1. Role-based aria-label search ──────────────────────────────
        aria_patterns = [
            re.compile(rf"^{month}\s+{day},\s+{year}$", re.IGNORECASE),
            re.compile(rf"\b{month}\s+{day}\b", re.IGNORECASE),
            day_re,
        ]
        for pat in aria_patterns:
            for role in ("button", "option", "gridcell"):
                el = page.get_by_role(role, name=pat).first  # type: ignore[arg-type]
                try:
                    if await el.count() > 0:
                        await el.click(force=True, timeout=4000)
                        return
                except Exception:
                    continue

        # ── 2. Ancestor-scoped text search ────────────────────────────────
        month_label = page.get_by_text(
            re.compile(rf"^{month}\s+{year}$", re.IGNORECASE)
        ).first
        if await month_label.count() > 0:
            for depth in range(1, 6):
                container = month_label.locator(f"xpath=ancestor::div[{depth}]")
                try:
                    if await container.count() == 0:
                        continue
                    # Try role-based first within the scoped container
                    for role in ("button", "option", "gridcell"):
                        day_el = container.get_by_role(role, name=day_re).first  # type: ignore[arg-type]
                        if await day_el.count() > 0:
                            await day_el.click(force=True, timeout=4000)
                            return
                    # Try any element whose FULL text is the day number
                    day_el = container.get_by_text(day_re).first
                    if await day_el.count() > 0:
                        await day_el.click(force=True, timeout=4000)
                        return
                except Exception:
                    continue

        # ── 3. JS fallback — walk the live DOM ───────────────────────────
        # Scope to the section containing the month heading so we don't
        # accidentally click a day number that appears elsewhere on the page
        # (e.g. the booking bar "Apr 22" would otherwise match day 22).
        clicked = await page.evaluate(f"""
            (function() {{
                // Find the element whose visible text is exactly the month+year
                const allEls = Array.from(document.querySelectorAll('*'));
                const monthEl = allEls.find(el =>
                    (el.innerText || '').trim() === {json.dumps(month_year)}
                );
                if (!monthEl) return false;

                // Walk up to find a container that also holds the day grid
                let container = monthEl;
                for (let i = 0; i < 6; i++) {{
                    container = container.parentElement;
                    if (!container) break;

                    // Find leaf elements (no child elements) with the exact day number
                    const leaves = Array.from(container.querySelectorAll('*')).filter(el =>
                        el.childElementCount === 0 &&
                        (el.innerText || el.textContent || '').trim() === {json.dumps(day_str)}
                    );
                    if (leaves.length > 0) {{
                        leaves[0].click();
                        return true;
                    }}
                }}
                return false;
            }})()
        """)
        if clicked:
            return

        raise RuntimeError(f"Could not click day {day} in {month} {year}")

    async def _set_date_range(
        self, page: Page, start: _DateParts, end: _DateParts
    ) -> None:
        await self._open_datepicker(page)

        await self._ensure_month_visible(page, start.month, start.year)
        await self._click_day_in_visible_month(page, start.month, start.year, start.day)
        await page.wait_for_timeout(400)

        await self._ensure_month_visible(page, end.month, end.year)
        await self._click_day_in_visible_month(page, end.month, end.year, end.day)
        await page.wait_for_timeout(400)

        # The popup usually closes itself once the end date is selected.
        # If it's still open after 3s, force-close it — otherwise
        # _wait_for_booking_bar_dates will read a stale / partial bar.
        closed = False
        for _ in range(15):
            if not await self._is_datepicker_open(page):
                closed = True
                break
            await page.wait_for_timeout(200)
        if not closed:
            logger.debug("Datepicker still open after end-date click — force-closing")
            await self._close_datepicker(page)
            await page.wait_for_timeout(300)

    async def _wait_for_booking_bar_dates(
        self, page: Page, start: _DateParts, end: _DateParts, timeout_ms: int = 20_000
    ) -> None:
        # Ensure the datepicker is closed before reading the bar — if it's open
        # the bar text may not have settled yet, and _get_date_range_locator can
        # find date strings inside the popup instead of the bar itself.
        await self._close_datepicker(page)
        await page.wait_for_timeout(400)

        regexes = _build_booking_bar_regexes(start, end)
        elapsed = 0
        last = ""
        while elapsed < timeout_ms:
            last = await self._read_booking_bar_text(page)
            if regexes["range"].search(last) or (
                regexes["start"].search(last) and regexes["end"].search(last)
            ):
                # Let the Site List table refresh in response.
                await page.wait_for_timeout(800)
                return
            await page.wait_for_timeout(250)
            elapsed += 250

        await self.snapshot(page, "booking_bar_did_not_update")
        raise TimeoutError(
            f"Booking bar did not update to target range. Last saw: {last!r}"
        )

    # ---------------------------------------------------------------- #
    # Site-list table parsing
    # ---------------------------------------------------------------- #

    async def _get_site_list_table(self, page: Page) -> Locator:
        """Locate the main Site List table.

        Some DOC facilities render summary rows like "Available # of People" /
        "Number of sites available"; others render only per-unit rows. Anchor
        on the "Site List" section first, then fall back to any visible table
        whose first header looks like a site-name column.
        """
        site_list_heading = page.get_by_text(
            re.compile(r"^Site List$", re.IGNORECASE)
        ).first
        try:
            await site_list_heading.wait_for(state="visible", timeout=20_000)
            for depth in range(1, 7):
                container = site_list_heading.locator(f"xpath=ancestor::div[{depth}]")
                table = container.locator("table").first
                if await table.count() > 0:
                    await table.wait_for(state="visible", timeout=5_000)
                    return table
        except PlaywrightTimeoutError:
            pass

        table = page.locator("table").filter(
            has_text=re.compile(r"\bSite\b", re.IGNORECASE)
        ).first
        await table.wait_for(state="visible", timeout=20_000)
        return table

    async def _wait_for_table_change(self, page: Page, timeout_ms: int = 20_000) -> None:
        """Wait for the Site List table to refresh after selecting dates."""
        siteListHeading = page.get_by_text(
            re.compile(r"^Site List$", re.IGNORECASE)
        ).first
        try:
            await siteListHeading.wait_for(state="visible", timeout=20_000)
            container = siteListHeading.locator(
                "xpath=ancestor::div[contains(., 'Maximum Capacity')][1]"
            ).first
        except PlaywrightTimeoutError:
            # No "Site List" heading — fall back to the table itself.
            container = await self._get_site_list_table(page)

        try:
            before = _normalize(await container.inner_text())
        except Exception:
            return

        elapsed = 0
        while elapsed < timeout_ms:
            try:
                last = _normalize(await container.inner_text())
            except Exception:
                last = before
            if last != before:
                await page.wait_for_timeout(1200)
                return
            await page.wait_for_timeout(300)
            elapsed += 300

    async def _extract_column_data(
        self, page: Page, hut_name: str, target_day: int
    ) -> dict:
        """Parse the Site List table and pull the cells for ``target_day``.

        Returns a dict with ``ok=True`` plus either summary-row cell data
        (hut-style / campsite-summary pages) or ``unit_cells`` for per-unit
        campsite grids. Returns ``ok=False`` + ``reason`` otherwise.
        """
        table = await self._get_site_list_table(page)
        rows = table.locator("tr")
        row_count = await rows.count()

        target_dd = str(target_day).zfill(2)
        col_idx = -1
        seen_rows: list[list[str]] = []

        for i in range(row_count):
            cells = rows.nth(i).locator("th, td")
            cell_count = await cells.count()
            texts: list[str] = []
            for j in range(cell_count):
                try:
                    raw = await cells.nth(j).inner_text()
                except Exception:
                    raw = ""
                txt = _normalize(raw)
                texts.append(txt)

                # Recognise the day-header column. DOC renders this cell as
                # "06", "6", "F 06", "Fri 06", etc. — accept any of them.
                if col_idx == -1 and (
                    txt == target_dd
                    or txt == str(target_day)
                    or re.search(rf"\b{target_dd}$", txt)
                ):
                    col_idx = j
            seen_rows.append(texts)

        if col_idx == -1:
            return {
                "ok": False,
                "reason": f"Could not find target day column {target_dd}",
                "seen_rows": seen_rows[:12],
            }

        site_row_idx = -1
        people_row_idx = -1
        sites_row_idx = -1
        unit_row_indices: list[int] = []

        for i, row_cells in enumerate(seen_rows):
            first = row_cells[0] if row_cells else ""
            row_len = len(row_cells)
            if site_row_idx == -1 and hut_name in first and row_len > col_idx:
                site_row_idx = i
            if (
                people_row_idx == -1
                and re.search(r"Available # of People", first, re.IGNORECASE)
                and row_len > col_idx
            ):
                people_row_idx = i
            if (
                sites_row_idx == -1
                and re.search(r"Number of sites available", first, re.IGNORECASE)
                and row_len > col_idx
            ):
                sites_row_idx = i
            if (
                row_len > col_idx
                and first
                and not re.search(
                    r"^(Site|Available # of People|Number of sites available)$",
                    first,
                    re.IGNORECASE,
                )
            ):
                unit_row_indices.append(i)

        async def _read_cell(row_idx: int) -> dict:
            if row_idx < 0 or col_idx < 0:
                return {"text": "", "html": ""}
            cell = rows.nth(row_idx).locator("th, td").nth(col_idx)
            try:
                text = _normalize(await cell.inner_text())
            except Exception:
                text = ""
            try:
                html = await cell.inner_html()
            except Exception:
                html = ""
            return {"text": text, "html": html}

        site_cell = await _read_cell(site_row_idx)
        people_cell = await _read_cell(people_row_idx)
        sites_cell = await _read_cell(sites_row_idx)
        unit_cells: list[dict] = []
        for row_idx in unit_row_indices:
            row_cells = rows.nth(row_idx).locator("th, td")
            try:
                site_name = _normalize(await row_cells.nth(0).inner_text())
            except Exception:
                site_name = ""
            if not site_name or site_name == hut_name:
                continue
            cell = await _read_cell(row_idx)
            unit_cells.append(
                {
                    "site_name": site_name,
                    "text": cell["text"],
                    "html": cell["html"],
                }
            )

        return {
            "ok": True,
            "col_idx": col_idx,
            "site_cell_text": site_cell["text"],
            "site_cell_html": site_cell["html"],
            "people_cell_text": people_cell["text"],
            "sites_cell_text": sites_cell["text"],
            "unit_cells": unit_cells,
            "debug": {
                "site_row_idx": site_row_idx,
                "people_row_idx": people_row_idx,
                "sites_row_idx": sites_row_idx,
                "unit_row_count": len(unit_cells),
            },
        }

    def _classify(
        self, parsed: dict, hut_name: str, people_wanted: int
    ) -> AvailabilityResult:
        """Turn parsed cell text/html into an AvailabilityResult.

        Mirrors the heuristic in ``detectMuellerAvailability`` in watch.ts
        but uses the three-state status enum (AVAILABLE / PARTIALLY_AVAILABLE
        / UNAVAILABLE) introduced by the Great Walk adapter so downstream
        notification logic can treat both adapters uniformly.
        """
        if not parsed.get("ok"):
            return AvailabilityResult(
                site=hut_name,
                status=AvailabilityStatus.UNKNOWN,
                evidence=parsed.get("reason", "Could not parse Site List table"),
            )

        people_text = (parsed.get("people_cell_text") or "").strip()
        sites_text = (parsed.get("sites_cell_text") or "").strip()
        site_cell_text = (parsed.get("site_cell_text") or "").strip()
        site_cell_html = parsed.get("site_cell_html") or ""

        people_num = int(people_text) if re.fullmatch(r"\d+", people_text) else None
        sites_num = int(sites_text) if re.fullmatch(r"\d+", sites_text) else None

        unit_cells = parsed.get("unit_cells") or []
        cell_is_bookable, aria_status, icon = _parse_site_cell_status(site_cell_html)

        logger.debug(
            "_classify: hut=%r people=%r sites=%r icon=%r bookable=%s aria_status=%r",
            hut_name, people_text, sites_text, icon, cell_is_bookable, aria_status,
        )

        if not cell_is_bookable or re.search(r"booked|closed|unavailable|not.available", aria_status):
            return AvailabilityResult(
                site=hut_name,
                status=AvailabilityStatus.UNAVAILABLE,
                evidence=(
                    f"Site cell not bookable online. "
                    f"tabindex0={cell_is_bookable} aria_status={aria_status!r} "
                    f"icon={icon!r}"
                ),
                icon=icon,
            )

        # ── Cell is clickable → determine capacity ────────────────────────────
        # DOC facilities use one of two rows to show how many spots remain:
        #   • "Available # of People"  — hut-style (beds/bunks)
        #   • "Number of sites available" — campsite-style
        # Prefer people count; fall back to site count.  Either > 0 confirms
        # the date is genuinely bookable (the clickable button already told us).

        count = people_num if people_num is not None else sites_num
        count_source = "people" if people_num is not None else "sites"

        if count is not None:
            if count_source == "sites":
                avail_status = (
                    AvailabilityStatus.AVAILABLE
                    if count > 0
                    else AvailabilityStatus.UNAVAILABLE
                )
            elif count >= people_wanted:
                avail_status = AvailabilityStatus.AVAILABLE
            elif count > 0:
                avail_status = AvailabilityStatus.PARTIALLY_AVAILABLE
            else:
                avail_status = AvailabilityStatus.UNAVAILABLE
            return AvailabilityResult(
                site=hut_name,
                status=avail_status,
                evidence=(
                    f"{count_source}={count!r} peopleCell={people_text!r} "
                    f"sitesCell={sites_text!r} icon={icon!r}"
                ),
                total_available=count,
                icon=icon,
            )

        if unit_cells:
            available_units = 0
            sample_icon = icon
            sample_statuses: list[str] = []
            for unit in unit_cells:
                unit_html = unit.get("html") or ""
                unit_bookable, unit_status, unit_icon = _parse_site_cell_status(unit_html)
                if unit_bookable:
                    available_units += 1
                if unit_status:
                    sample_statuses.append(f"{unit.get('site_name')}: {unit_status}")
                if sample_icon is None and unit_icon is not None:
                    sample_icon = unit_icon

            avail_status = (
                AvailabilityStatus.AVAILABLE
                if available_units > 0
                else AvailabilityStatus.UNAVAILABLE
            )
            return AvailabilityResult(
                site=hut_name,
                status=avail_status,
                evidence=(
                    f"unitCells available={available_units}/{len(unit_cells)} "
                    f"sampleStatuses={sample_statuses[:4]!r}"
                ),
                total_available=available_units,
                icon=sample_icon,
            )

        return AvailabilityResult(
            site=hut_name,
            status=AvailabilityStatus.UNKNOWN,
            evidence=(
                f"Ambiguous state. peopleCell={people_text!r} "
                f"sitesCell={sites_text!r} siteCell={site_cell_text!r} "
                f"icon={icon!r}"
            ),
            icon=icon,
        )

    # ---------------------------------------------------------------- #
    # BaseDOCAdapter API
    # ---------------------------------------------------------------- #

    async def _target_day_in_visible_table(self, page: Page, target_day: int) -> bool:
        """Return True if *target_day* already has a column in the Site List table.

        The DOC site loads a default date window (typically ~3 weeks from
        tomorrow).  If the job's target day falls inside that window we can
        read availability directly without touching the datepicker at all.
        """
        try:
            table = await self._get_site_list_table(page)
            # The header row contains day numbers — look for an exact match
            header_row = table.locator("tr").first
            cells = header_row.locator("th, td")
            count = await cells.count()
            target_dd = str(target_day).zfill(2)
            for i in range(count):
                txt = _normalize(await cells.nth(i).inner_text())
                if txt == target_dd or txt == str(target_day) or txt.endswith(target_dd):
                    return True
        except Exception:
            pass
        return False

    async def fill_form(self, page: Page, params: dict) -> None:
        url = self._url_for(params)
        await page.goto(url, wait_until="domcontentloaded", timeout=60_000)
        try:
            await page.wait_for_load_state("networkidle", timeout=30_000)
        except PlaywrightTimeoutError:
            pass
        # DOC's SPA needs a beat to hydrate the booking bar / selected facility.
        await page.wait_for_timeout(5000)

        start, end = self._date_range(params)
        before = await self._read_booking_bar_text(page)
        logger.info(f"Standard-hut booking bar before selection: {before}")

        # Fast path: if the target start date is already a column in the visible
        # Site List table we don't need to touch the datepicker at all.
        # This covers the common case where the job date falls in the ~3-week
        # default window the DOC site loads (avoids the flaky picker entirely).
        if await self._target_day_in_visible_table(page, start.day):
            logger.info(
                "Target day %s is already in the visible table — skipping datepicker",
                start.day,
            )
            # Close the auto-opened datepicker so it doesn't obscure the table
            await self._close_datepicker(page)
            return

        regexes = _build_booking_bar_regexes(start, end)
        already = bool(
            regexes["range"].search(before)
            or (regexes["start"].search(before) and regexes["end"].search(before))
        )

        if not already:
            try:
                await self._set_date_range(page, start, end)
            except Exception as e:
                logger.warning(
                    f"set_date_range failed (continuing with whatever range is "
                    f"currently selected): {e}"
                )
        else:
            logger.info("Booking bar already matches target range — skipping picker")

        # Even when we skipped the picker, verify the bar reflects the target
        # range before we try to parse the table. A mismatch here means the
        # page loaded pointing at an unrelated range and _set_date_range
        # didn't actually update it.
        await self._wait_for_booking_bar_dates(page, start, end)

        # Give the Site List table time to refresh after a range change.
        try:
            await self._wait_for_table_change(page)
        except Exception as e:
            logger.info(f"Site List table change wait non-fatal: {e}")

    async def detect_availability(
        self, page: Page, params: dict
    ) -> list[AvailabilityResult]:
        """One hut per job.

        Unlike Great Walks (where one job naturally covers multiple huts
        along a track), standard-hut jobs are scoped to a single facility.
        If you want to watch two huts, create two jobs. The return type is
        still ``list[AvailabilityResult]`` to match ``BaseAdapter``'s
        contract — callers already handle the "all AVAILABLE" /
        "any AVAILABLE" / partial cases generically.
        """
        try:
            _park_id, _facility_id, hut_name = self._resolve_site(params)
        except ValueError as e:
            return [AvailabilityResult(
                site="(unspecified)",
                status=AvailabilityStatus.UNKNOWN,
                evidence=str(e),
            )]

        people_wanted = int(params.get("people", 2))
        start, _end = self._date_range(params)
        parsed = await self._extract_column_data(page, hut_name, start.day)
        return [self._classify(parsed, hut_name, people_wanted)]

    # ---------------------------------------------------------------- #
    # attempt_hold — standard flow (best-effort port)
    # ---------------------------------------------------------------- #

    async def attempt_hold(self, page: Page, params: dict) -> BookingResult:
        """Drive the "regular" DOC hold flow.

        The non-Great-Walk booking flow differs from the Great Walk one:
        instead of clicking a cell in the ``table.js-book-modal`` grid, the
        user clicks the site column in the Site List to reveal a per-site
        booking panel, sets a quantity, presses an "Add to Booking" / "Book
        Now" button, then continues through login → occupant details →
        Shopping Cart → CreditCardPayment.

        The selectors for the per-site panel are not documented in the
        watch.ts script (it only did availability detection), so this
        implementation anchors on visible text ("Book Now", "Add to
        Booking", "Continue", "Reserve") and falls back to role-based
        matching. Once the flow reaches ``CreditCardPayment`` we reuse the
        Great Walk adapter's cart-capture logic verbatim. If any step
        fails, we snapshot the page and return a non-held BookingResult so
        the caller notifies the user.
        """
        try:
            _park_id, _facility_id, hut_name = self._resolve_site(params)
        except ValueError as e:
            return BookingResult(success=False, held=False, message=str(e))

        people_wanted = int(params.get("people", 2))
        occupants = params.get("occupants", [])
        job_id_for_cart = params.get("_job_id", "unknown")
        start, _end = self._date_range(params)

        if not occupants:
            return BookingResult(
                success=False,
                held=False,
                message="No occupant details provided — cannot complete hold",
            )

        # --- 1. Click the site row button for the target date ----------- #
        # DOC renders each date cell as a <button> with an aria-label of the
        # form "{Site Name} MM/DD/YYYY - available".  Targeting by aria-label
        # is far more reliable than computing row/column indices through a
        # flex-layout table that can't be navigated with nth().
        month_num = MONTHS.index(start.month) + 1
        target_date_str = f"{month_num:02d}/{start.day:02d}/{start.year}"

        # Build candidates in order of specificity:
        #   1. Exact site-name + date match on a bookable cell
        #   2. Any bookable cell for the target date (campsite unit grids)
        #   3. Non-bookable fallbacks for diagnostics only
        site_btn = page.locator(
            f'button[aria-label*="{hut_name}"][aria-label*="{target_date_str}"][tabindex="0"]'
        )
        if await site_btn.count() == 0:
            site_btn = page.locator(
                f'button[aria-label*="{target_date_str}"][tabindex="0"]'
            ).filter(has=page.locator("img"))

        if await site_btn.count() == 0:
            site_btn = page.locator(
                f'button[aria-label*="{hut_name}"][aria-label*="{target_date_str}"]'
            )

        if await site_btn.count() == 0:
            # Fallback: any button whose aria-label contains the date and
            # contains an <img> (icon), excluding the datepicker buttons which
            # have no img child.
            site_btn = page.locator(
                f'button[aria-label*="{target_date_str}"]'
            ).filter(has=page.locator("img"))

        if await site_btn.count() == 0:
            await self.snapshot(page, "hold_no_site_button")
            return BookingResult(
                success=False,
                held=False,
                message=(
                    f"Could not find site button for {hut_name!r} on "
                    f"{target_date_str} — no matching aria-label"
                ),
            )

        btn = site_btn.first
        try:
            await btn.scroll_into_view_if_needed(timeout=10_000)
            await btn.evaluate("el => el.click()")
            logger.info(
                "Selected availability cell for %s on %s (aria-label targeting)",
                hut_name, target_date_str,
            )
        except Exception as e:
            await self.snapshot(page, "hold_cell_click_failed")
            return BookingResult(
                success=False,
                held=False,
                message=f"Could not click availability cell: {e}",
            )

        await page.wait_for_timeout(600)

        # --- 2. Click "Book Now" to proceed from the site list -------- #
        # For campsite-style facilities, clicking the date cell SELECTS it
        # (the cell turns into "Booking Selected") but the page stays on the
        # Site List.  The user must then click "Book Now" at the bottom of
        # the table to proceed.  Hut-style facilities may skip this step and
        # navigate directly to a booking form — handled below.
        _BOOK_NOW_RE = re.compile(
            r"^(Book Now|Add to Booking|Add to Cart)$", re.IGNORECASE
        )
        book_now_btn = page.get_by_role("button", name=_BOOK_NOW_RE).first
        try:
            await book_now_btn.wait_for(state="visible", timeout=6_000)
            await book_now_btn.click()
            logger.info("Clicked Book Now to proceed from site list")
            await page.wait_for_timeout(600)
        except PlaywrightTimeoutError:
            logger.info("No Book Now button found — assuming direct navigation after cell click")

        # --- 3. Handle login if prompted ------------------------------ #
        # Clicking "Book Now" (or the cell itself for huts) will trigger the
        # login modal when the user isn't authenticated.  After a successful
        # login, DOC stays on the current page — no re-click needed since the
        # site remembers the selection.
        try:
            await self._login_if_prompted(page)
            await page.wait_for_timeout(600)
        except RuntimeError as e:
            await self.snapshot(page, "login_error")
            return BookingResult(success=False, held=False, message=str(e))

        # --- 4. Detect which booking form appeared -------------------- #
        # Pattern A — Campsite "Reservation Details" inline form:
        #   After login (or if already logged in), DOC shows a page with a
        #   "Reserve Unit" button, adult-count select, and occupant name input.
        #
        # Pattern B — Hut / Great Walk occupant modal:
        #   An "Occupant Details" modal appears with per-person name/age fields.

        _RESERVE_UNIT_RE = re.compile(r"Reserve\s+Unit", re.IGNORECASE)
        reserve_unit_btn = page.get_by_role("button", name=_RESERVE_UNIT_RE)
        try:
            await reserve_unit_btn.wait_for(state="visible", timeout=15_000)
            is_campsite_form = True
            logger.info("Detected Reservation Details page (Reserve Unit button)")
        except PlaywrightTimeoutError:
            is_campsite_form = False

        if is_campsite_form:
            # ── Pattern A: fill the inline Reservation Details page ── #

            # 4a. Set adult count
            # DOC's adult-count select has aria-label="Adult (18+)" directly on
            # the <select> element (not a wrapping label).  Use that attribute to
            # target it precisely — other selects (Nights, Child, Infant) have
            # different aria-labels.
            try:
                adult_select = page.locator('select[aria-label*="Adult" i]').first
                if await adult_select.count() == 0:
                    # Fallback: select whose id ends in ddlPersonClassification_0
                    adult_select = page.locator(
                        'select[id$="ddlPersonClassification_0"]'
                    ).first
                await adult_select.select_option(str(people_wanted))
                logger.info("Set adult count to %d", people_wanted)
                await page.wait_for_timeout(400)
            except Exception as e:
                logger.warning("Could not set adult count: %s", e)

            # 4b. Fill "Occupant Name" (required — must be ≥ 3 chars)
            # DOC uses id="mainContent_txtOccupant" / placeholder="Enter occupant name".
            occ_name = ""
            if occupants:
                first = occupants[0].get("first_name", "")
                last = occupants[0].get("last_name", "")
                occ_name = f"{first} {last}".strip() or first or last
            if not occ_name:
                occ_name = "Guest"
            try:
                name_input = page.locator("#mainContent_txtOccupant").first
                if await name_input.count() == 0:
                    name_input = page.locator('[placeholder="Enter occupant name"]').first
                if await name_input.count() == 0:
                    name_input = page.locator('[aria-label="Occupant Name"]').first
                await name_input.wait_for(state="visible", timeout=5_000)
                await name_input.fill(occ_name)
                logger.info("Filled occupant name: %r", occ_name)
            except Exception as e:
                logger.warning("Could not fill occupant name: %s", e)

            # 4c. Accept T&C checkbox
            try:
                tc_checkbox = page.get_by_label(
                    re.compile(r"agree.*terms|terms.*conditions", re.IGNORECASE)
                ).first
                if await tc_checkbox.count() == 0:
                    tc_checkbox = page.locator('input[type="checkbox"]').first
                if not await tc_checkbox.is_checked():
                    await tc_checkbox.check()
                    logger.info("Checked T&C checkbox")
            except Exception as e:
                logger.warning("Could not check T&C checkbox: %s", e)

            await self.snapshot(page, "reservation_details")

            # 4d. Click "Reserve Unit"
            try:
                await reserve_unit_btn.click()
                logger.info("Clicked Reserve Unit")
                # DOC shows a "Message" validation dialog if required fields are
                # missing (e.g. "Occupant Name - must be at least 3 characters").
                # Detect it and surface a clear error rather than timing out later.
                await page.wait_for_timeout(800)
                msg_dialog = page.locator(".modal, [role='dialog']").filter(
                    has_text=re.compile(r"Fill in the following|must be at least", re.IGNORECASE)
                ).first
                if await msg_dialog.count() > 0 and await msg_dialog.is_visible():
                    msg_text = await msg_dialog.inner_text()
                    logger.warning("Reservation validation error: %s", msg_text.strip())
                    await self.snapshot(page, "reserve_unit_validation_error")
                    # Try to close the dialog
                    close_btn = msg_dialog.locator("button").first
                    if await close_btn.count() > 0:
                        await close_btn.click()
                    return BookingResult(
                        success=False, held=False,
                        message=f"Reservation form validation error: {msg_text.strip()[:200]}",
                    )
            except Exception as e:
                await self.snapshot(page, "reserve_unit_click_failed")
                return BookingResult(
                    success=False, held=False,
                    message=f"Could not click Reserve Unit: {e}",
                )

        else:
            # ── Pattern B: Occupant Details modal (hut-style) ──────── #
            try:
                await page.locator("text=Occupant Details").first.wait_for(
                    state="visible", timeout=10_000
                )
                logger.info("Occupant details modal appeared")
            except PlaywrightTimeoutError:
                await self.snapshot(page, "occupant_modal_timeout")
                return BookingResult(
                    success=False, held=False,
                    message="Neither Reserve Unit page nor Occupant Details modal appeared",
                )

            await self._fill_occupants(page, occupants)

            await page.get_by_role("button", name="Save & Continue").click()
            logger.info("Clicked Save & Continue")

        # --- 6. Intermediate Reservation Details page (hut/Great Walk only) -- #
        # For campsite Pattern A, clicking "Reserve Unit" navigates directly to
        # the Shopping Cart — there is no intermediate SelectReservationPreCart
        # step.  Only run this block for Pattern B (hut/Great Walk modal flow).
        if not is_campsite_form:
            try:
                await page.wait_for_url(
                    re.compile(r"SelectReservationPreCart", re.IGNORECASE),
                    timeout=15_000,
                )
                logger.info("Reached Reservation Details page")
            except PlaywrightTimeoutError:
                await self.snapshot(page, "reservation_details_url_timeout")
                return BookingResult(
                    success=False,
                    held=False,
                    message="Did not reach Reservation Details page",
                )

            try:
                book_link = page.locator("#mainContent_bReserve")
                await book_link.wait_for(state="visible", timeout=15_000)

                view_occ_btn = page.locator("#aViewOccupant")
                if await view_occ_btn.count() > 0:
                    await view_occ_btn.click()
                    logger.info("Opened View Occupants modal")
                    await page.locator("#myModal_occu").wait_for(
                        state="visible", timeout=5_000
                    )
                    await page.wait_for_timeout(300)
                    await self.snapshot(page, "reservation_details")
                    await page.locator("#myModal_occu .close").first.click()
                    await page.locator("#myModal_occu").wait_for(
                        state="hidden", timeout=5_000
                    )
                else:
                    await self.snapshot(page, "reservation_details")

                await book_link.click()
                logger.info("Clicked reserve (#mainContent_bReserve)")
            except PlaywrightTimeoutError:
                await self.snapshot(page, "reserve_link_timeout")
                return BookingResult(
                    success=False,
                    held=False,
                    message="Reserve link not found on Reservation Details page",
                )

        try:
            await page.wait_for_url("**/ShoppingCart**", timeout=15_000)
            logger.info("Reached Shopping Cart")
        except PlaywrightTimeoutError:
            await self.snapshot(page, "shopping_cart_timeout")
            return BookingResult(
                success=False,
                held=False,
                message="Did not reach Shopping Cart page",
            )

        await self._check_terms(page)

        cart_url = await self._proceed_to_checkout(page)
        if cart_url is None:
            return BookingResult(
                success=False, held=False,
                message="Did not reach payment page",
            )

        resume_url = await self._persist_cart_session(page, job_id_for_cart, cart_url)
        return BookingResult(
            success=True,
            held=True,
            reservation_url=resume_url,
            message=(
                f"Cart secured for {hut_name} on {params.get('date')}. "
                f"24 minutes to complete payment."
            ),
        )
